components: 
  wavefront:
    name: Wavefront
    profile:
      model: GaussianWavefront
      size: 512
      sigma: 128
    physical:
      energy: 10.0 
      spacing: 0.0001
      position: 0.0
      
  optic:
    name: Optic
    profile:
      model: CodedOptic
      size: 512
      bit_size: 64
      seed: 0
    physical:
      formula: Au
      density: 19.3
      thickness: 0.0001
      position: 0.0

  sample:
    name: Sample
    profile:
      model: LenaProfile
      size: 512
    physical:
      formula: C5H8O2
      density: 1.18
      thickness: 0.001
      position: 5.0

  detector:
    name: Detector
    physical:
      formula: Si
      density: 2.33
      thickness: 0.001
      position: 300.0
