# myconfig.yaml - Example configuration for wavefront simulation

experiment:
  - { component_id: "my_wavefront", geometry: { position: 0.0 } }
  - { component_id: "my_aperture", geometry: { position: 1.0 } }
  - { component_id: "my_sample", geometry: { position: 2.0 } }
  - { component_id: "my_detector", geometry: { position: 100.0 } }

operator:
  propagator: { type: "fresnel" }
  interactor: { type: "thin_object" }

simulation:
  wavefront:
    id: "my_wavefront"
    type: "constant"
    properties: { amplitude: 1.0, phase: 0.0, energy: 10.0, shape: 512, spacing: 0.0001 }

  optic:
    id: "my_aperture"
    type: "coded_aperture"
    properties: { material: "Au", density: 19.3, thickness: 0.0001, bit_size: 64 }

  sample:
    id: "my_sample"
    type: "custom_profile"
    properties: 
      material: "C5H8O2"
      density: 1.18
      thickness: 0.001
      custom_profile: "coho/resources/samples/lena.npy"

  detector: { id: "my_detector", type: "integrating" }

optimization:
  objective: { id: "my_objective", type: "least_squares" }
  solver:
    id: "my_solver"
    type: "gradient_descent"
    properties: { step_size: 0.01, iterations: 100 }
