experiment:
  type: dict
  required: true
  schema:
    id:
      type: string
      required: true
    model:
      type: string
      required: true
    properties:
      type: dict
      required: false
      default: {}
      schema:
        components:
          type: list
          required: true
        workflow:
          type: dict
          required: true
          schema:
            steps:
              type: list
              required: true
              schema:
                type: dict
                schema:
                  action:
                    type: string
                    required: true
                    allowed: ['initialize', 'collect', 'finalize']
