# config/schemas/experiment.yaml

experiment:
  type: dict
  required: true
  schema:
    id:
      type: string
      required: true
    model:
      type: string
      required: true
    properties:
      type: dict
      required: false
      default: {}
      schema:
        components:
          type: list
          required: true
        scan:
          type: dict
          required: false
          default: {}
          schema:
            sweeps:
              type: list
              required: false
              default: []
              schema:
                type: dict
                schema:
                  component:
                    type: string
                    required: true
                  parameters:
                    type: list
                    required: true
                    schema:
                      type: dict
                      schema:
                        path:
                          type: string
                          required: true
                        range:
                          type: list
                          required: true
                          schema:
                            type: number
            order:
              type: list
              required: false
              default: []
              schema:
                type: integer