# config/schemas/experiment.yaml

experiment:
  type: dict
  required: true
  schema:
    id:
      type: string
      required: true
    model:
      type: string
      required: true
    properties:
      type: dict
      required: false
      default: {}
      schema:
        components:
          type: list
          required: true
        scans:
          type: dict
          required: false
          default: {}
          schema:
            targets:
              type: list
              required: false
              default: []
            sweeps:
              type: dict
              required: false
              default: {}
              keysrules:
                type: string
              valuesrules:
                type: dict
                schema:
                  start: {type: number, required: true}
                  end: {type: number, required: true}
                  step: {type: number, required: true}
            order:
              type: list
              required: false
              default: []
              schema:
                type: string