# config/schemas/operator.yaml

operator:
  type: dict
  required: true
  schema:

    interactor:
      type: dict
      required: true
      schema:
        id:
          type: string
          required: false
        model:
          type: string
          required: true
          allowed: ["thin_object", "thick_object"]
        properties:
          type: dict
          required: true
          default: {}

    propagator:
      type: dict
      required: true
      schema:
        id:
          type: string
          required: false
        model:
          type: string
          required: true
          allowed: ["fresnel", "fraunhofer"]
        properties:
          type: dict
          required: true
          default: {}
