# config/schemas/simulation.yaml

simulation:
  type: dict
  required: true
  schema:

    wavefront:
      type: dict
      required: true
      schema:
        id:
          type: string
          required: true
        model:
          type: string
          required: true
          allowed: ["constant", "gaussian", "rectangular"]
        properties:
          type: dict
          required: false
          default: {}
          schema:
            physical:
              type: dict
              required: false
              default: {}
              schema:
                amplitude: {type: float, min: 0.0, required: false, default: 1.0}
                phase: {type: float, required: false, default: 0.0}
                energy: {type: float, min: 0.0, required: false, default: 10.0}
            profile:
              type: dict
              required: false
              default: {}
              schema:
                sigma: {type: float, min: 0.0, required: false, default: 256}
                width: {type: float, min: 0.0, required: false, default: 256}
                height: {type: float, min: 0.0, required: false, default: 256}
            grid:
              type: dict
              required: false
              default: {}
              schema:
                size: {type: integer, min: 1, required: false, default: 512}
                spacing: {type: float, min: 0.0, required: false, default: 0.001}
            geometry:
              type: dict
              required: false
              default: {}
              schema:
                position:
                  type: dict
                  required: false
                  default: {}
                  schema:
                    x: {type: float, required: false, default: 0.0}
                    y: {type: float, required: false, default: 0.0}
                    z: {type: float, required: false, default: 0.0}
                rotation: {type: float, required: false, default: 0.0}

    optic:
      type: dict
      required: false
      default: {}
      schema:
        id:
          type: string
          required: true
        model:
          type: string
          required: true
          allowed: ["coded_aperture", "slit_aperture", "circle_aperture", "custom_profile"]
        properties:
          type: dict
          required: false
          default: {}
          schema:
            physical:
              type: dict  
              required: false
              default: {}
              schema:
                formula: {type: string, required: false, default: "Au"}
                density: {type: float, min: 0.0, required: false, default: 19.3}
                thickness: {type: float, min: 0.0, required: false, default: 0.0001}
            profile:
              type: dict
              required: false
              default: {}
              schema:
                model: {type: string, required: false, default: "binary_random"}
                bit_size: {type: integer, min: 1, required: false, default: 64}
                seed: {type: integer, required: false, default: 0}
                width: {type: float, min: 0.0, required: false, default: 256}
                height: {type: float, min: 0.0, required: false, default: 256}
            grid:
              type: dict
              required: false
              default: {}
              schema:
                size: {type: integer, min: 1, required: false, default: 512}
                spacing: {type: float, min: 0.0, required: false, default: 0.001}
            geometry:
              type: dict
              required: false
              default: {}
              schema:
                position:
                  type: dict
                  required: false
                  default: {}
                  schema:
                    x: {type: float, required: false, default: 0.0}
                    y: {type: float, required: false, default: 0.0}
                    z: {type: float, required: false, default: 0.0}
                rotation: {type: float, required: false, default: 0.0}
            
    sample:
      type: dict
      required: false
      schema:
        id:
          type: string
          required: true
        model:
          type: string
          required: true
          allowed: ["custom_profile"]
        properties:
          type: dict
          required: false
          default: {}
          schema:
            physical:
              type: dict
              required: false
              default: {}
              schema:
                formula: {type: string, required: false, default: "C5H8O2"}
                density: {type: float, min: 0.0, required: false, default: 1.18}
                thickness: {type: float, min: 0.0, required: false, default: 0.001}
            profile:
              type: dict
              required: false
              default: {}
              schema:
                model: {type: string, required: false, default: "custom_profile"}
                file_path: {type: string, required: false, default: "coho/resources/samples/lena.npy"}
            grid:
              type: dict
              required: false
              default: {}
              schema:
                size: {type: integer, min: 1, required: false, default: 512}
                spacing: {type: float, min: 0.0, required: false, default: 0.001}
            geometry:
              type: dict
              required: false
              default: {}
              schema:
                position:
                  type: dict
                  required: true
                  schema:
                    x: {type: float, required: false, default: 0.0}
                    y: {type: float, required: false, default: 0.0}
                    z: {type: float, required: false, default: 0.0}
                rotation: {type: float, required: false, default: 0.0}

    detector:
      type: dict
      required: true
      schema:
        id:
          type: string
          required: true
        model:
          type: string
          required: true
          allowed: ["integrating", "photon_counting"]
        properties:
          type: dict
          required: false
          default: {}
          schema:
            grid:
              type: dict
              required: false
              default: {}
              schema:
                size: {type: integer, min: 1, required: false, default: 512}
                spacing: {type: float, min: 0.0, required: false, default: 0.001}
            geometry:
              type: dict
              required: false
              default: {}
              schema:
                position:
                  type: dict
                  required: false
                  default: {}
                  schema:
                    x: {type: float, required: false, default: 0.0}
                    y: {type: float, required: false, default: 0.0}
                    z: {type: float, required: false, default: 0.0}
                rotation: {type: float, required: false, default: 0.0}
