# Example configuration for a holography simulation

experiment:
  id: "my_experiment"
  model: "holography"
  properties:
    components:
      - "my_wavefront"
      - "my_aperture"
      - "my_sample"
      - "my_detector"


simulation:
  wavefront:
    id: my_wavefront
    model: constant
    properties:
      physical:
        amplitude: 1.0
        phase: 1.0
        energy: 10.0
      grid:
        size: 512
        spacing: 0.0001
      geometry:
        position:
          z: 0.0

  optic:
    id: "my_aperture"
    model: "coded_aperture"
    properties:
      physical:
        formula: "Au"
        density: 19.3
        thickness: 0.0001
      profile:
        model: "binary_random"
        bit_size: 64
        seed: 0
      geometry:
        position:
          z: 1.0

  sample:
    id: "my_sample"
    model: "custom_profile"
    properties:
      physical:
        formula: "C5H8O2"
        density: 1.18
        thickness: 0.001
      profile:
        model: "custom_profile"
        file_path: "coho/resources/samples/lena.npy"
      geometry:
        position:
          z: 2.0

  detector:
    id: "my_detector"
    model: "integrating"
    properties: 
      geometry:
        position:
          z: 100.0

operator:
  propagator:
    id: "my_propagator"
    model: "fresnel"

  interactor:
    id: "my_interactor"
    model: "thin_object"
